---
- name: Gather Interface Facts from Cisco IOS XR Device
  hosts: ios_device
  gather_facts: no
  tasks:
    - name: Gather IOS XR facts
      cisco.iosxr.iosxr_facts:
        gather_subset: '!all'
        gather_network_resources: interfaces
      register: result

    - name: Print interfaces
      debug:
        var: result.ansible_facts.ansible_net_interfaces