---
- name: get-config
  connection: network_cli
  gather_facts: false
  hosts: ios_device

  tasks:
    - name: Get config for IOS devices
      cisco.iosxr.iosxr_command:
        commands: show run
      register: result

    - name: Display the config
      debug: msg="{{ result }}"